export const ADD_COLUMN = "ADD_COLUMN";
export const DELETE_COLUMN = "DELETE_COLUMN";
export const CHANGE_COLUMN_TITLE = "CHANGE_COLUMN_TITLE";

export const ADD_TASK = "ADD_TASK";
export const CHANHE_TASK_TITLE = "CHANHE_TASK_TITLE";
