export const ADD_COLUMN = "ADD_COLUMN";
export const DELETE_COLUMN = "DELETE_COLUMN";
export const CHANGE_COLUMN_TITLE = "CHANGE_COLUMN_TITLE";

export const ADD_TASK = "ADD_TASK";
export const CHANGE_TASK_TITLE = "CHANGE_TASK_TITLE";

export const TASK_DND_SAME_COLUMN = "TASK_DND_SAME_COLUMN";
export const TASK_DND_DIFFERENT_COLUMN = "TASK_DND_DIFFERENT_COLUMN";

export const COLUMN_DND = "COLUMN_DND";
